-- 다대다관계
-- 학생테이블, 과목테이블을 참조하는 수강신청 테이블

DROP TABLE ENROLL;
DROP TABLE STUDENT1;
DROP TABLE SUBJECT;

-- 학생 테이블
CREATE TABLE STUDENT1(
    STU_NO CHAR(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE CHAR(2 BYTE) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);

-- 과목 테이블
CREATE TABLE SUBJECT(
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(20 BYTE) NOT NULL,
    SUB_PRO VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
);

-- 수강신청 테이블
CREATE TABLE ENROLL(
    ENR_NO CHAR(1 BYTE) NOT NULL,
    STU_NO CHAR(5 BYTE) NOT NULL,
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO),
    CONSTRAINT FK_ENROLL_SUTDENT1 FOREIGN KEY(STU_NO) REFERENCES STUDENT1(STU_NO),
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)
);