DROP TABLE PROJECT2;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT1;
DROP TABLE DEPARTMENT;

-- 부서 테이블
CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO)
);

-- 프로젝트 테이블
CREATE TABLE PROJECT1(
    PJT_NO NUMBER NOT NULL, 
    PJT_NAME VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE NULL,
    END_DATE DATE NULL,
    CONSTRAINT PK_PROJECT1 PRIMARY KEY(PJT_NO)
);

-- 사원 테이블
CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE) NULL,
    POSITIO CHAR(10 BYTE) NULL,
    EMP_NAME VARCHAR2(15 BYTE) NULL,
    HIRE_DATE DATE NULL,
    SALARY NUMBER NULL,
   CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO),
   CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO)
);

-- 프로젝트 진행
CREATE TABLE PROJECT2(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER NULL,
    PJT_NO NUMBER NULL,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PROJECT2 PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PROJECT2_EMPLOYEE FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT FK_PROJECT2_PROJECT1 FOREIGN KEY(PJT_NO) REFERENCES PROJECT1(PJT_NO)
);
