DROP TABLE PROJECT2;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT1;
DROP TABLE DEPARTMENT;

-- 부서 테이블
CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL
);

-- 프로젝트 테이블
CREATE TABLE PROJECT1(
    PJT_NO NUMBER NOT NULL, 
    PJT_NAME VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE NULL,
    END_DATE DATE NULL
);

-- 사원 테이블
CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    POSITIO CHAR(10 BYTE) NULL,
    EMP_NAME VARCHAR2(15 BYTE) NULL,
    HIRE_DATE DATE NULL,
    SALARY NUMBER NULL
);

-- 프로젝트 진행
CREATE TABLE PROJECT2(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER NULL,
    PJT_NO NUMBER NULL,
    PJT_STATE NUMBER NOT NULL
);

-- 기본키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);
ALTER TABLE PROJECT1
    ADD CONSTRAINT PK_PROJECT1 PRIMARY KEY(PJT_NO);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO);
ALTER TABLE PROJECT2
    ADD CONSTRAINT PK_PROJECT2 PRIMARY KEY(PCD_NO);

-- 외래키 추가
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO)
        REFERENCES DEPARTMENT(DEPT_NO);
ALTER TABLE PROJECT2
    ADD CONSTRAINT FK_PROJECT2_PROJECT1 FOREIGN KEY(PJT_NO)
        REFERENCES PROJECT1(PJT_NO);
ALTER TABLE PROJECT2
    ADD CONSTRAINT FK_PROJECT2_EMPLOYEE FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEE(EMP_NO);


-- 외래키 제거
-- DEPARTMENT 테이블의 DEPT_NO 칼럼을 참조하는 외래키 제약조건을 제거해야
-- DEPARTMENT 테이블의 DEPT_NO 칼럼에 추가된 기본키 제약조건을 제거할 수 있음
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;
    
-- 기본키 제거
-- FK에 의해서 참조되고 있는 PK는 제거할 수 없음
-- 먼저 FK를 제거해야 함
ALTER TABLE DEPARTMENT
    DROP PRIMARY KEY; --EMPLOYEE의 FK를 먼저 제거해야 실행할 수 있음
ALTER TABLE PROJECT1
    DROP PRIMARY KEY;


/*
  상속된 외래키-기본키 순서대로 정리
  
ALTER TABLE PROJECT2
    DROP CONSTRAINT FK_PROJECT2_PROJECT1;
ALTER TABLE PROJECT2
    DROP CONSTRAINT FK_PROJECT2_EMPLOYEE;
ALTER TABLE PROJECT2
    DROP CONSTRAINT PK_PROJECT2;
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT PK_EMPLOYEE;
ALTER TABLE PROJECT1
    DROP PRIMARY KEY;
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT;
*/
